/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apress_example_Unix */

#ifndef _Included_com_apress_example_Unix
#define _Included_com_apress_example_Unix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apress_example_Unix
 * Method:    getlogin
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_apress_example_Unix_getlogin
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
